#!/bin/bash

# Check if the required parameters are provided
if [[ $# -ne 4 ]]; then
  echo "Usage: ./0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Get the path to the file to be transferred
file_path=$1

# Get the IP of the server
server_ip=$2

# Get the username to connect with
username=$3

# Get the path to the SSH private key
ssh_key_path=$4

# Disable strict host key checking
ssh-keyscan -H $server_ip > ~/.ssh/known_hosts
sed -i '/$server_ip/d' ~/.ssh/known_hosts

# Transfer the file to the server
scp -o StrictHostKeyChecking=no -i $ssh_key_path $file_path $username@$server_ip:~/


