#!/usr/bin/env bash
# debugging nginx port 80
rm /etc/nginx/sites-enabled/default
# configure ngnix
In -s /etc/nginx/site-available/default/etc/nginx/site-enabled/default
# restart nginix
service nginx restart